# Generated by Django 6.0.5 on 2026-05-25 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP"),
                            ("UTILITY", "UTILITY"),
                            ("TRAVEL", "TRAVEL"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "upload_method",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("API", "API")], max_length=50
                    ),
                ),
                (
                    "original_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_by", models.CharField(max_length=255)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PROCESSING",
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_payload", models.JSONField()),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("VALID", "VALID"),
                            ("FLAGGED", "FLAGGED"),
                            ("INVALID", "INVALID"),
                        ],
                        default="VALID",
                        max_length=50,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="ingestion.datasourceupload",
                    ),
                ),
            ],
        ),
    ]
