"""
Django settings for config project.

Generated by 'django-admin startproject'
using Django 6.0.5.
"""

from pathlib import Path

import dj_database_url


# Build paths inside the project
BASE_DIR = (
    Path(__file__)
    .resolve()
    .parent.parent
)


# SECURITY WARNING:
# keep the secret key used in production secret!

SECRET_KEY = (
    "django-insecure-"
    "m3f@84(pa3@q3))flzuuyp9gkiu"
    "@ev48w*!+d)g2t_t$&p9j99"
)


# SECURITY WARNING:
# don't run with debug turned on in production!

DEBUG = True


ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",

    "core",
    "ingestion",
    "emissions",
    "audit",
    "analytics_dashboard",
]


MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# DATABASE CONFIG
# Local:
# localhost postgres
#
# Production:
# Render DATABASE_URL

DATABASES = {

    "default": dj_database_url.config(

        default=(
            "postgresql://postgres:"
            "Anwesha123@localhost:5432/"
            "esg-prototype"
        ),

        conn_max_age=600
    )
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        (
            "django.contrib.auth."
            "password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },

    {
        "NAME":
        (
            "django.contrib.auth."
            "password_validation."
            "MinimumLengthValidator"
        ),
    },

    {
        "NAME":
        (
            "django.contrib.auth."
            "password_validation."
            "CommonPasswordValidator"
        ),
    },

    {
        "NAME":
        (
            "django.contrib.auth."
            "password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = "static/"


# CORS

CORS_ALLOW_ALL_ORIGINS = True


# Default primary key field type

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)