# Generated by Django 6.0.5 on 2026-05-25 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizedEmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP"),
                            ("UTILITY", "UTILITY"),
                            ("TRAVEL", "TRAVEL"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("FUEL", "FUEL"),
                            ("ELECTRICITY", "ELECTRICITY"),
                            ("FLIGHT", "FLIGHT"),
                            ("HOTEL", "HOTEL"),
                            ("RENTAL_CAR", "RENTAL_CAR"),
                            ("PROCUREMENT", "PROCUREMENT"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "SCOPE_1"),
                            ("SCOPE_2", "SCOPE_2"),
                            ("SCOPE_3", "SCOPE_3"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("normalized_quantity", models.FloatField()),
                ("normalized_unit", models.CharField(max_length=50)),
                ("activity_date", models.DateField()),
                ("facility_location", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("FLAGGED", "FLAGGED"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "raw_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="ingestion.rawrecord",
                    ),
                ),
            ],
        ),
    ]
